"use client";
import { FormEvent, useEffect, useState } from "react";
import { getSignedInUser, signIn, signInWithGoogle, signOut, signUpDentist } from "../lib/supabase/auth";
import { createClinic, getCurrentMembership } from "../lib/supabase/dentmemo";

type View = "today"|"patients"|"calendar"|"followups"|"insights"|"more"|"visit";
type Role = "dentist"|"assistant";
const pts=[
 {id:"DM-00421",i:"AR",name:"Anjali Rao",phone:"98765 43210",last:"Today",tx:"Root canal",tooth:"36",c:"purple"},
 {id:"DM-00420",i:"RK",name:"Rahul Kumar",phone:"98223 33445",last:"10 Aug",tx:"Scaling",tooth:"—",c:"green"},
 {id:"DM-00419",i:"MI",name:"Meera Iyer",phone:"87654 32109",last:"9 Aug",tx:"Crown",tooth:"16",c:"orange"},
 {id:"DM-00418",i:"SN",name:"Suresh Naik",phone:"90909 87654",last:"8 Aug",tx:"Filling",tooth:"27",c:"rose"},
 {id:"DM-00417",i:"MF",name:"Maria Fernandes",phone:"99221 14567",last:"8 Aug",tx:"Implant",tooth:"46",c:"pink"}
];
const slots=[
 ["10:00 AM","Anjali Rao","RCT · Obturation","In progress"],
 ["11:30 AM","Rahul Kumar","Scaling","Confirmed"],
 ["01:00 PM","Meera Iyer","Crown trial","Confirmed"],
 ["02:30 PM","Suresh Naik","Filling","Confirmed"]
];

function Logo(){return <div className="logo"><span className="mark">♡</span><b>DentMemo<small>Second brain for dentists</small></b></div>}
function Av({p,sm=false}:{p:typeof pts[number],sm?:boolean}){return <span className={`av ${p.c} ${sm?"sm":""}`}>{p.i}</span>}
function Button({children,soft=false,onClick}:{children:React.ReactNode,soft?:boolean,onClick?:()=>void}){return <button onClick={onClick} className={soft?"btn soft":"btn"}>{children}</button>}

function Onboarding({done,startAtClinic=false,initialName=""}:{done:()=>void,startAtClinic?:boolean,initialName?:string}){
 const [step,setStep]=useState(startAtClinic?2:1),[name,setName]=useState(initialName),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[clinic,setClinic]=useState(""),[city,setCity]=useState(""),[registrationNumber,setRegistrationNumber]=useState(""),[wa,setWa]=useState(true),[cal,setCal]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loginMode,setLoginMode]=useState(false);
 const next=(e?:FormEvent)=>{e?.preventDefault();setStep(Math.min(6,step+1))};
 const submitAccount=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");setNotice("");try{const result=loginMode?await signIn(email,password):await signUpDentist({email,password,fullName:name});if(result.error)throw result.error;if(!result.data.session){setNotice("Check your email and confirm your account, then return here and log in.");setLoginMode(true);return}const membership=await getCurrentMembership();if(membership){done();return}setStep(2)}catch(err){setError(err instanceof Error?err.message:"Could not continue. Please try again.")}finally{setLoading(false)}};
 const googleLogin=async()=>{setLoading(true);setError("");try{const result=await signInWithGoogle();if(result.error)throw result.error}catch(err){setError(err instanceof Error?err.message:"Google login could not start.");setLoading(false)}};
 const submitClinic=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{await createClinic({name:clinic,city,registrationNumber});setStep(3)}catch(err){setError(err instanceof Error?err.message:"Could not create your clinic.")}finally{setLoading(false)}};
 const labels=["Account","Clinic","Essentials","Calendar","Reminders","Ready"];
 return <main className="onboarding"><header><Logo/></header>
  <div className="steps">{labels.map((x,i)=><div className={i+1<=step?"active":""} key={x}><i>{i+1<step?"✓":i+1}</i><span>{x}</span></div>)}</div>
  <section className="setup">
   {step===1&&<form onSubmit={submitAccount}><div className="setup-logo"><Logo/></div><p className="eyebrow">{loginMode?"WELCOME BACK":"START FREE"}</p><h1>{loginMode?"Log in to DentMemo":"Create your account"}</h1><p className="muted">{loginMode?"Continue to your clinic.":"No credit card. Set up your clinic in under 3 minutes."}</p><button type="button" className="btn soft" onClick={googleLogin} disabled={loading}>Continue with Google</button><p className="legal">or use email and password</p>{!loginMode&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={loginMode?"current-password":"new-password"} minLength={8} required/></label>{error&&<p className="form-error" role="alert">{error.includes("Invalid login credentials")?"This account may use Google sign-in. Tap Continue with Google above, or switch to Create account.":error}</p>}{notice&&<p className="form-notice" role="status">{notice}</p>}<Button>{loading?"Please wait…":loginMode?"Log in":"Create account"}</Button><button type="button" className="link" onClick={()=>{setLoginMode(!loginMode);setError("");setNotice("")}}>{loginMode?"New to DentMemo? Create an account":"Already have an account? Log in"}</button><small className="legal">By continuing, you agree to our Terms and Privacy Policy.</small></form>}
   {step===2&&<form onSubmit={submitClinic}><p className="eyebrow">STEP 2 OF 6</p><h1>Create your clinic</h1><p className="muted">These details appear on appointments and reminders.</p><label>Clinic name<input value={clinic} onChange={e=>setClinic(e.target.value)} required/></label><label>City<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Margao, Goa" required/></label><div className="columns"><label>Primary dentist<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Registration no.<input value={registrationNumber} onChange={e=>setRegistrationNumber(e.target.value)} placeholder="Optional"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button>{loading?"Creating clinic…":"Continue"}</Button></form>}
   {step===3&&<div><p className="eyebrow">MAKE IT YOURS</p><h1>Set up essentials</h1><p className="muted">You can change this later.</p><label>Treatments you offer</label><div className="chips">{["Root canal","Scaling","Filling","Extraction","Crown & bridge","Implant","Consultation"].map(x=><button key={x}>{x} ×</button>)}</div><button className="add">＋ Add treatment</button><label>Clinic hours</label><div className="hours"><span>Mon – Sat</span><span>09:00 AM</span><em>to</em><span>07:00 PM</span></div><button className="invite">＋ Invite an assistant later</button><Button onClick={()=>next()}>Continue</Button></div>}
   {step===4&&<div className="center"><div className="integration cal">31</div><h1>Connect Google Calendar</h1><p className="muted">See DentMemo appointments in Google Calendar and keep changes in sync both ways.</p><div className="benefits"><span>✓ Avoid double-booking</span><span>✓ Work from your existing calendar</span><span>✓ Disconnect anytime</span></div><Button onClick={()=>{setCal(true);next()}}>Connect Google Calendar</Button><button className="link" onClick={()=>next()}>Skip for now</button></div>}
   {step===5&&<div className="center"><div className="integration wa">◉</div><h1>WhatsApp reminders</h1><p className="muted">Send one-way reminders to reduce no-shows. No chat inbox is added.</p><div className="toggle-row"><span><b>Enable reminders</b><small>24 hours before appointment</small></span><button onClick={()=>setWa(!wa)} className={`toggle ${wa?"on":""}`}><i/></button></div><div className="message">Hi {"{patient_name}"}, this is a reminder for your appointment on {"{date}"} at {"{time}"}.<br/><br/>Regards,<br/>{clinic}</div><Button onClick={()=>next()}>Continue</Button><button className="link" onClick={()=>{setWa(false);next()}}>Skip for now</button></div>}
   {step===6&&<div className="center"><div className="success">✓</div><p className="eyebrow">WELCOME, {name.toUpperCase()}</p><h1>Your clinic is ready!</h1><p className="muted">{clinic} is set up{cal?" with Calendar sync":""}{wa?" and WhatsApp reminders":""}.</p><Button onClick={done}>Open DentMemo</Button><div className="ready-links"><span>＋ Add your first patient</span><span>▣ Create an appointment</span></div></div>}
  </section><footer><span>🔒 Secure by design</span><span>7-day trial</span><span>Cancel anytime</span><span>Made for dentists</span></footer>
 </main>
}

function Nav({view,setView,role}:{view:View,setView:(v:View)=>void,role:Role}){
 const items:[View,string,string][]=[["today","⌂","Today"],["patients","♙","Patients"],["calendar","□","Calendar"],["followups","◷","Follow-ups"],...(role==="dentist"?[["insights","↗","Insights"] as [View,string,string]]:[])];
 return <>{items.map(([v,i,l])=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}><i>{i}</i><span>{l}</span></button>)}</>
}
function Shell({children,view,setView,role,setRole}:{children:React.ReactNode,view:View,setView:(v:View)=>void,role:Role,setRole:(r:Role)=>void}){
 return <div className="app"><aside><Logo/><div className="clinic"><span className="av purple sm">B</span><span><b>Blessin Dental Studio</b><small>{role==="dentist"?"Primary dentist":"Assistant workspace"}</small></span></div><nav><Nav {...{view,setView,role}}/></nav><Button onClick={()=>setView(role==="dentist"?"visit":"calendar")}>＋ {role==="dentist"?"Quick visit":"Appointment"}</Button><div className="aside-bottom"><button className={view==="more"?"active":""} onClick={()=>setView("more")}><i>☷</i><span>More</span></button><button className="role" onClick={()=>{setRole(role==="dentist"?"assistant":"dentist");setView("today")}}>Switch to {role==="dentist"?"assistant":"dentist"} view</button></div></aside>
  <div className="mobile-head"><button>☰</button><Logo/><button>♧<i>3</i></button></div><main className="workspace">{children}</main><nav className="mobile-nav"><button className={view==="today"?"active":""} onClick={()=>setView("today")}><i>⌂</i><span>Today</span></button><button className={view==="patients"?"active":""} onClick={()=>setView("patients")}><i>♙</i><span>Patients</span></button><button className="plus" onClick={()=>setView(role==="dentist"?"visit":"calendar")}>＋</button><button className={view==="followups"?"active":""} onClick={()=>setView("followups")}><i>◷</i><span>{role==="dentist"?"Follow-ups":"Calendar"}</span></button><button className={view==="more"?"active":""} onClick={()=>setView("more")}><i>☷</i><span>More</span></button></nav></div>
}
function Title({children,sub,action}:{children:React.ReactNode,sub?:string,action?:React.ReactNode}){return <header className="title"><div><h1>{children}</h1>{sub&&<p>{sub}</p>}</div>{action}</header>}
function Search(){return <div className="search">⌕<input placeholder="Search patient, phone or tooth…"/></div>}
function Schedule(){return <section className="panel schedule"><div className="panel-title"><h2>Today’s schedule</h2><button>See calendar</button></div>{slots.map((s,i)=><div className="slot" key={s[0]}><time>{s[0]}</time><i className={`bar c${i}`}/><span><b>{s[1]}</b><small>{s[2]}</small></span><em className={i?"confirmed":"progress"}>{s[3]}</em></div>)}</section>}
function Today({role,setView}:{role:Role,setView:(v:View)=>void}){const a=role==="assistant";return <><Title sub="Tuesday, 11 August" action={<Button onClick={()=>setView(a?"calendar":"visit")}>＋ {a?"Appointment":"Quick visit"}</Button>}>Good morning, {a?"Anita":"Dr. Blessin"} 👋</Title><Search/><div className="metrics"><article><i className="blue">♙</i><b>6</b><small>Patients today</small></article><article><i className="green">{a?"✓":"₹"}</i><b>{a?"4":"₹8,400"}</b><small>{a?"Confirmed":"Collected"}</small></article><article><i className="red">◷</i><b>{a?"1":"2"}</b><small>{a?"Waiting":"Follow-ups due"}</small></article></div><div className="dash"><Schedule/><section className="panel"><div className="panel-title"><h2>{a?"Front desk tasks":"Continue where you left off"}</h2></div>{a?<div className="tasks"><label><input type="checkbox"/> Confirm Rahul’s appointment</label><label><input type="checkbox"/> Call Maria about crown arrival</label><label><input type="checkbox"/> Collect pending ₹1,500</label></div>:<div className="spotlight"><div><Av p={pts[0]}/><span><b>Anjali Rao</b><small>36 · Root canal treatment</small></span><em>In progress</em></div><p><b>Last visit:</b> Access opening completed. Pain reduced. Temporary filling placed.</p><p className="next"><b>Next:</b> Obturation</p><button onClick={()=>setView("patients")}>Open patient →</button></div>}</section></div></>}

function Patients(){const [chosen,setChosen]=useState<typeof pts[number]|null>(null),[q,setQ]=useState("");if(chosen)return <Profile p={chosen} back={()=>setChosen(null)}/>;return <><Title sub="81 patients in your clinic" action={<Button>＋ New patient</Button>}>Patients</Title><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, phone, ID or tooth…"/></div><section className="panel patient-list">{pts.filter(p=>(p.name+p.phone+p.tooth).toLowerCase().includes(q.toLowerCase())).map(p=><button key={p.id} onClick={()=>setChosen(p)}><Av p={p}/><span><b>{p.name}</b><small>{p.id} · {p.phone}</small><em>Last visit: {p.last}</em></span><i>{p.tx}</i><strong>›</strong></button>)}</section></>}
function Profile({p,back}:{p:typeof pts[number],back:()=>void}){const [tab,setTab]=useState("Snapshot");return <><button className="back" onClick={back}>← All patients</button><Title sub={`${p.id} · ${p.phone}`} action={<div className="contact"><button>☎</button><button>◉</button><button>•••</button></div>}>{p.name}</Title><div className="patient-summary"><Av p={p}/><span><b>29Y, Female</b><small>✓ No known allergies</small></span><em>Under treatment</em></div><div className="tabs">{["Snapshot","Teeth","Timeline","Plan","Payments"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="Snapshot"&&<div className="details"><section className="panel clinical"><div className="panel-title"><h2>Clinical snapshot</h2><em>In progress</em></div><h3>♡ {p.tooth} · {p.tx}</h3><dl><div><dt>Started</dt><dd>29 Jul 2026</dd></div><div><dt>Next action</dt><dd>Obturation</dd></div><div><dt>Clinical note</dt><dd>Pain reduced. Temporary restoration intact.</dd></div></dl></section><Timeline/></div>}{tab==="Teeth"&&<Teeth/>}{tab==="Timeline"&&<Timeline/>}{tab==="Plan"&&<Plan/>}{tab==="Payments"&&<Payments/>}</>}
function Timeline(){return <section className="panel timeline"><div className="panel-title"><h2>Timeline</h2><button>Filter</button></div>{[["11 Aug · Today","36 · RCT","Obturation completed. Working length 21mm.","₹2,000"],["4 Aug","36 · RCT","Biomechanical preparation. Temporary filling placed.","₹2,000"],["29 Jul","36","RCT initiated. Access opening done.","₹1,500"]].map(x=><article key={x[0]}><i/><time>{x[0]}</time><div><b>{x[1]}</b><p>{x[2]}</p><small>{x[3]} · Dr. Blessin</small></div></article>)}</section>}
function Teeth(){const nums=[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28,48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];return <section className="panel teeth"><div className="panel-title"><h2>Tooth chart</h2><span>● In progress　● Completed　● Planned</span></div><div className="tooth-grid">{nums.map(n=><button className={n===36?"current":n===16?"planned":""} key={n}><small>{n}</small>♢</button>)}</div><div className="tooth-info"><h3>Tooth 36</h3><dl><div><dt>Diagnosis</dt><dd>Irreversible pulpitis</dd></div><div><dt>Treatment</dt><dd>Root canal treatment</dd></div><div><dt>Status</dt><dd><em>In progress</em></dd></div><div><dt>Visits</dt><dd>3</dd></div></dl></div></section>}
function Plan(){return <section className="panel plan"><div className="panel-title"><h2>Treatment plan</h2><button>＋ Add item</button></div>{[["36","Root canal treatment","In progress","₹6,500"],["16","Composite filling","Planned","₹1,500"],["—","Scaling","Completed","₹1,200"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span><em>{x[2]}</em><strong>{x[3]}</strong></div>)}</section>}
function Payments(){return <section className="panel payments"><div><span><small>Total treatment</small><b>₹9,200</b></span><span><small>Collected</small><b>₹5,500</b></span><span><small>Outstanding</small><b className="red-text">₹3,700</b></span></div><Button>Record payment</Button></section>}

function QuickVisit({done}:{done:()=>void}){const [s,setS]=useState(1);return <section className="quick"><header><button onClick={done}>×</button><b>Quick visit <small>{s} of 4</small></b></header><div className="quick-progress"><i style={{width:`${s*25}%`}}/></div>{s===1&&<div><h1>Who are you seeing?</h1><p className="muted">Search or choose a recent patient.</p><Search/><div className="recent">{pts.slice(0,3).map((p,i)=><button className={i===0?"active":""} key={p.id}><Av p={p} sm/><span><b>{p.name}</b><small>{p.phone}</small></span><i>✓</i></button>)}</div></div>}{s===2&&<div><h1>What are you doing today?</h1><div className="chips"><button>Treatment</button><button>Consultation</button><button>Review</button></div><label>Tooth<input defaultValue="36"/></label><label>Treatment<select><option>Root canal treatment</option><option>Scaling</option><option>Filling</option></select></label><label>Status<select><option>In progress</option><option>Completed</option></select></label></div>}{s===3&&<div><h1>Clinical note</h1><p className="muted">Capture only what matters.</p><textarea defaultValue="36 obturation completed. Patient comfortable. Recall after one week."/><div className="note-tools"><button>🎙 Dictate</button><button>▤ Templates</button><span>83 / 1000</span></div><label>Follow-up<select><option>In 1 week</option><option>Tomorrow</option><option>None</option></select></label></div>}{s===4&&<div><h1>Payment <small>(optional)</small></h1><label>Treatment fee<input defaultValue="₹2,000"/></label><label>Amount received<input defaultValue="₹2,000"/></label><label>Payment method<select><option>UPI</option><option>Cash</option><option>Card</option></select></label><div className="visit-summary"><Av p={pts[0]}/><span><b>Anjali Rao</b><small>36 · Root canal · In progress</small></span></div></div>}<footer>{s>1&&<Button soft onClick={()=>setS(s-1)}>Back</Button>}<Button onClick={()=>s<4?setS(s+1):done()}>{s<4?"Continue":"Save visit"}</Button></footer></section>}
function Calendar({role}:{role:Role}){const [toast,setToast]=useState(false);return <><Title sub="Tuesday, 11 August" action={<Button onClick={()=>setToast(true)}>＋ Appointment</Button>}>Calendar</Title>{toast&&<div className="toast">Appointment form ready for Calendar sync.<button onClick={()=>setToast(false)}>×</button></div>}<section className="panel day-calendar"><div className="times">{["09:00 AM","10:00 AM","11:00 AM","12:00 PM","01:00 PM","02:00 PM","03:00 PM","04:00 PM"].map(x=><span key={x}>{x}</span>)}</div><div className="events">{slots.map((x,i)=><article className={`e${i}`} style={{top:`${50+i*66}px`}} key={x[1]}><b>{x[0]} · {x[1]}</b><span>{x[2]}</span>{role==="assistant"&&<small>{x[3]}</small>}</article>)}</div></section></>}
function Followups(){return <><Title sub="Patients needing attention">Follow-ups</Title><div className="tabs"><button className="active">Today (3)</button><button>Overdue (2)</button><button>This week (8)</button></div><section className="panel patient-list">{pts.slice(0,4).map((p,i)=><button key={p.id}><Av p={p}/><span><b>{p.name}</b><small>{i===0?"Extraction · Review due today":i===1?"Crown · Lab expected tomorrow":"RCT · No visit for 14 days"}</small></span><i>{["10:30 AM","12:00 PM","3:00 PM","Tomorrow"][i]}</i><strong>›</strong></button>)}</section></>}
function Insights(){return <><Title sub="This month · 1–11 August">Insights</Title><div className="insight-grid">{[["Collected","₹78,400","↑ 12% vs July"],["Patient visits","81","↑ 8% vs July"],["Average revenue / visit","₹968","↑ 10% vs July"],["Most performed","19","Root canals"]].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></article>)}</div><section className="panel attention"><h2>Needs attention</h2><div>{[["₹","₹13,500","Outstanding"],["◷","8","Overdue follow-ups"],["♙","4","Cases waiting for plan"]].map(x=><article key={x[2]}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]}</small></article>)}</div></section></>}
function More({role,setRole,exit}:{role:Role,setRole:(r:Role)=>void,exit:()=>void}){return <><Title>More</Title><section className="panel profile"><span className="av purple">B</span><span><b>Blessin Dental Studio</b><small>Margao, Goa · {role==="dentist"?"Dr. Blessin":"Anita, Assistant"}</small></span></section><section className="panel menu">{["Treatments","Team & access","Clinic settings","Calendar & reminders","Data export","Billing & subscription","Help & support","Security & privacy"].map(x=><button key={x}>{x}<i>›</i></button>)}<button onClick={()=>setRole(role==="dentist"?"assistant":"dentist")}>Preview {role==="dentist"?"assistant":"dentist"} experience<i>›</i></button><button className="signout" onClick={exit}>Sign out<i>›</i></button></section></>}

export default function Home(){const [inApp,setInApp]=useState(false),[signedIn,setSignedIn]=useState(false),[signedInName,setSignedInName]=useState(""),[checkingSession,setCheckingSession]=useState(true),[role,setRole]=useState<Role>("dentist"),[view,setView]=useState<View>("today");useEffect(()=>{Promise.all([getCurrentMembership(),getSignedInUser()]).then(([m,u])=>{setInApp(Boolean(m));setSignedIn(Boolean(u));setSignedInName(u?String(u.user_metadata?.full_name||u.user_metadata?.name||""):"")}).catch(()=>setInApp(false)).finally(()=>setCheckingSession(false))},[]);const exit=async()=>{await signOut();setInApp(false);setSignedIn(false);setSignedInName("");setView("today")};if(checkingSession)return <main className="onboarding"><section className="setup"><div className="center"><Logo/><p className="muted">Opening DentMemo…</p></div></section></main>;if(!inApp)return <Onboarding done={()=>setInApp(true)} startAtClinic={signedIn} initialName={signedInName}/>;const content=view==="today"?<Today {...{role,setView}}/>:view==="patients"?<Patients/>:view==="calendar"?<Calendar role={role}/>:view==="followups"?<Followups/>:view==="insights"?<Insights/>:view==="visit"?<QuickVisit done={()=>setView("today")}/>:<More role={role} setRole={setRole} exit={exit}/>;return <Shell {...{view,setView,role,setRole}}>{content}</Shell>}
