"use client";
import "./rebuild.css";
import { FormEvent, useState } from "react";

type View = "today"|"patients"|"calendar"|"followups"|"overview"|"more"|"visit";
type Role = "dentist"|"assistant";
const pts=[
 {id:"DM-00421",i:"AR",name:"Anjali Rao",phone:"98765 43210",last:"Today",tx:"Root canal",tooth:"36",c:"purple"},
 {id:"DM-00420",i:"RK",name:"Rahul Kumar",phone:"98223 33445",last:"10 Aug",tx:"Scaling",tooth:"—",c:"green"},
 {id:"DM-00419",i:"MI",name:"Meera Iyer",phone:"87654 32109",last:"9 Aug",tx:"Crown",tooth:"16",c:"orange"},
 {id:"DM-00418",i:"SN",name:"Suresh Naik",phone:"90909 87654",last:"8 Aug",tx:"Filling",tooth:"27",c:"rose"},
 {id:"DM-00417",i:"MF",name:"Maria Fernandes",phone:"99221 14567",last:"8 Aug",tx:"Implant",tooth:"46",c:"pink"}
];
const slots=[
 ["10:00 AM","Anjali Rao","RCT · Obturation","In progress"],
 ["11:30 AM","Rahul Kumar","Scaling","Confirmed"],
 ["01:00 PM","Meera Iyer","Crown trial","Confirmed"],
 ["02:30 PM","Suresh Naik","Filling","Confirmed"]
];

function Logo(){return <div className="logo"><span className="mark">♡</span><b>DentMemo<small>Second brain for dentists</small></b></div>}
function Av({p,sm=false}:{p:typeof pts[number],sm?:boolean}){return <span className={`av ${p.c} ${sm?"sm":""}`}>{p.i}</span>}
function Button({children,soft=false,onClick}:{children:React.ReactNode,soft?:boolean,onClick?:()=>void}){return <button onClick={onClick} className={soft?"btn soft":"btn"}>{children}</button>}

function Onboarding({done}:{done:()=>void}){
 const [step,setStep]=useState(0),[clinic,setClinic]=useState("Blessin Dental Studio"),[dentist,setDentist]=useState("Dr. Blessin"),[city,setCity]=useState("Margao, Goa"),[pin,setPin]=useState("");
 const pages=[
  <div key="hello"><span className="notion-icon">🦷</span><p className="eyebrow">WELCOME TO DENTMEMO</p><h1>Let’s build your clinic memory.</h1><p className="muted">A calm workspace for patients, visits, consultants and follow-ups. We’ll set up only what you need.</p></div>,
  <div key="clinic"><span className="notion-icon">🏥</span><p className="eyebrow">YOUR CLINIC</p><h1>What should we call your workspace?</h1><label>Clinic name<input value={clinic} onChange={e=>setClinic(e.target.value)}/></label><div className="columns"><label>Primary dentist<input value={dentist} onChange={e=>setDentist(e.target.value)}/></label><label>City<input value={city} onChange={e=>setCity(e.target.value)}/></label></div></div>,
  <div key="workflow"><span className="notion-icon">✨</span><p className="eyebrow">YOUR WORKFLOW</p><h1>What matters every day?</h1><div className="choice-grid">{["Patient history","Quick visit notes","Consultant tracking","Payments","Follow-ups","Appointments"].map(x=><button className="selected" key={x}>✓ {x}</button>)}</div><p className="muted">These become your core workspace. You can adjust them later.</p></div>,
  <div key="pin"><span className="notion-icon">🔐</span><p className="eyebrow">PROTECT DENTIST VIEW</p><h1>Create a 4-digit clinic PIN.</h1><p className="muted">Assistants can use the daily workspace. Three taps on the clinic logo plus this PIN unlocks financial and consultant details.</p><label>Clinic PIN<input inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="••••"/></label></div>,
  <div key="ready"><span className="notion-icon">🚀</span><p className="eyebrow">READY</p><h1>Your workspace is ready.</h1><p className="muted">Start with today’s patients. DentMemo will quietly build the history around them.</p><div className="onb-summary"><b>{clinic}</b><span>{dentist} · {city}</span><small>Patients · Visits · Consultants · Follow-ups</small></div></div>
 ];
 const finish=()=>{localStorage.setItem("dentmemo_onboarded","1");localStorage.setItem("dentmemo_pin",pin||"2468");done()};
 return <main className="notion-onboarding"><header><Logo/><span>{step+1} of {pages.length}</span></header><div className="notion-progress"><i style={{width:`${((step+1)/pages.length)*100}%`}}/></div><section>{pages[step]}<footer>{step>0&&<Button soft onClick={()=>setStep(step-1)}>Back</Button>}<Button onClick={()=>step===pages.length-1?finish():setStep(step+1)}>{step===pages.length-1?"Enter DentMemo":"Continue"}</Button></footer></section></main>
}

function Nav({view,setView,role}:{view:View,setView:(v:View)=>void,role:Role}){
 const items:[View,string,string][]=[["today","⌂","Today"],["patients","♙","Patients"],["calendar","□","Calendar"],["followups","◷","Follow-ups"],...(role==="dentist"?[["overview","₹","Consultants"] as [View,string,string]]:[])];
 return <>{items.map(([v,i,l])=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}><i>{i}</i><span>{l}</span></button>)}</>
}
function Shell({children,view,setView,role,setRole}:{children:React.ReactNode,view:View,setView:(v:View)=>void,role:Role,setRole:(r:Role)=>void}){
 const [taps,setTaps]=useState(0),[pinOpen,setPinOpen]=useState(false),[pin,setPin]=useState(""),[pinError,setPinError]=useState("");
 const tapLogo=()=>{const n=taps+1;setTaps(n);window.setTimeout(()=>setTaps(0),1200);if(n>=3){setTaps(0);if(role==="dentist"){setRole("assistant");setView("today")}else setPinOpen(true)}};
 const unlock=(e:FormEvent)=>{e.preventDefault();if(pin===(localStorage.getItem("dentmemo_pin")||"2468")){setRole("dentist");setView("today");setPinOpen(false);setPin("");setPinError("")}else setPinError("Incorrect PIN")};
 return <div className="app"><aside><Logo/><button className="clinic clinic-button" onClick={tapLogo}><span className="av purple sm">B</span><span><b>Blessin Dental Studio</b><small>{role==="dentist"?"Dentist view · 3 taps to lock":"Assistant workspace · 3 taps to unlock"}</small></span></button><nav><Nav {...{view,setView,role}}/></nav><Button onClick={()=>setView(role==="dentist"?"visit":"calendar")}>＋ {role==="dentist"?"Quick visit":"Appointment"}</Button><div className="aside-bottom"><button className={view==="more"?"active":""} onClick={()=>setView("more")}><i>☷</i><span>More</span></button></div></aside>
  <div className="mobile-head"><button onClick={tapLogo} className="mobile-clinic-logo">B</button><Logo/><button>♧<i>3</i></button></div><main className="workspace">{children}</main><nav className="mobile-nav"><button className={view==="today"?"active":""} onClick={()=>setView("today")}><i>⌂</i><span>Today</span></button><button className={view==="patients"?"active":""} onClick={()=>setView("patients")}><i>♙</i><span>Patients</span></button><button className="plus" onClick={()=>setView(role==="dentist"?"visit":"calendar")}>＋</button><button className={view==="followups"?"active":""} onClick={()=>setView("followups")}><i>◷</i><span>{role==="dentist"?"Follow-ups":"Calendar"}</span></button><button className={view==="more"?"active":""} onClick={()=>setView("more")}><i>☷</i><span>More</span></button></nav>{pinOpen&&<div className="pin-overlay"><form onSubmit={unlock}><span>🔐</span><h2>Dentist access</h2><p>Enter the clinic PIN to open consultant and financial details.</p><input autoFocus inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="••••"/>{pinError&&<small>{pinError}</small>}<Button>Unlock</Button><button type="button" className="link" onClick={()=>setPinOpen(false)}>Cancel</button></form></div>}</div>
}
function Title({children,sub,action}:{children:React.ReactNode,sub?:string,action?:React.ReactNode}){return <header className="title"><div><h1>{children}</h1>{sub&&<p>{sub}</p>}</div>{action}</header>}
function Search(){return <div className="search">⌕<input placeholder="Search patient, phone or tooth…"/></div>}
function Schedule(){return <section className="panel schedule"><div className="panel-title"><h2>Today’s schedule</h2><button>See calendar</button></div>{slots.map((s,i)=><div className="slot" key={s[0]}><time>{s[0]}</time><i className={`bar c${i}`}/><span><b>{s[1]}</b><small>{s[2]}</small></span><em className={i?"confirmed":"progress"}>{s[3]}</em></div>)}</section>}
function Today({role,setView}:{role:Role,setView:(v:View)=>void}){const a=role==="assistant";return <><Title sub="Tuesday, 11 August" action={<Button onClick={()=>setView(a?"calendar":"visit")}>＋ {a?"Appointment":"Quick visit"}</Button>}>Good morning, {a?"Anita":"Dr. Blessin"} 👋</Title><Search/><div className="metrics"><article><i className="blue">♙</i><b>6</b><small>Patients today</small></article><article><i className="green">{a?"✓":"₹"}</i><b>{a?"4":"₹8,400"}</b><small>{a?"Confirmed":"Collected"}</small></article><article><i className="red">◷</i><b>{a?"1":"2"}</b><small>{a?"Waiting":"Follow-ups due"}</small></article></div><div className="dash"><Schedule/><section className="panel"><div className="panel-title"><h2>{a?"Front desk tasks":"Continue where you left off"}</h2></div>{a?<div className="tasks"><label><input type="checkbox"/> Confirm Rahul’s appointment</label><label><input type="checkbox"/> Call Maria about crown arrival</label><label><input type="checkbox"/> Collect pending ₹1,500</label></div>:<div className="spotlight"><div><Av p={pts[0]}/><span><b>Anjali Rao</b><small>36 · Root canal treatment</small></span><em>In progress</em></div><p><b>Last visit:</b> Access opening completed. Pain reduced. Temporary filling placed.</p><p className="next"><b>Next:</b> Obturation</p><button onClick={()=>setView("patients")}>Open patient →</button></div>}</section></div></>}

function Patients(){const [chosen,setChosen]=useState<typeof pts[number]|null>(null),[q,setQ]=useState("");if(chosen)return <Profile p={chosen} back={()=>setChosen(null)}/>;return <><Title sub="81 patients in your clinic" action={<Button>＋ New patient</Button>}>Patients</Title><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, phone, ID or tooth…"/></div><section className="panel patient-list">{pts.filter(p=>(p.name+p.phone+p.tooth).toLowerCase().includes(q.toLowerCase())).map(p=><button key={p.id} onClick={()=>setChosen(p)}><Av p={p}/><span><b>{p.name}</b><small>{p.id} · {p.phone}</small><em>Last visit: {p.last}</em></span><i>{p.tx}</i><strong>›</strong></button>)}</section></>}
function Profile({p,back}:{p:typeof pts[number],back:()=>void}){const [tab,setTab]=useState("Snapshot");return <><button className="back" onClick={back}>← All patients</button><Title sub={`${p.id} · ${p.phone}`} action={<div className="contact"><button>☎</button><button>◉</button><button>•••</button></div>}>{p.name}</Title><div className="patient-summary"><Av p={p}/><span><b>29Y, Female</b><small>✓ No known allergies</small></span><em>Under treatment</em></div><div className="tabs">{["Snapshot","Teeth","Timeline","Plan","Payments"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="Snapshot"&&<div className="details"><section className="panel clinical"><div className="panel-title"><h2>Clinical snapshot</h2><em>In progress</em></div><h3>♡ {p.tooth} · {p.tx}</h3><dl><div><dt>Started</dt><dd>29 Jul 2026</dd></div><div><dt>Next action</dt><dd>Obturation</dd></div><div><dt>Clinical note</dt><dd>Pain reduced. Temporary restoration intact.</dd></div></dl></section><Timeline/></div>}{tab==="Teeth"&&<Teeth/>}{tab==="Timeline"&&<Timeline/>}{tab==="Plan"&&<Plan/>}{tab==="Payments"&&<Payments/>}</>}
function Timeline(){return <section className="panel timeline"><div className="panel-title"><h2>Timeline</h2><button>Filter</button></div>{[["11 Aug · Today","36 · RCT","Obturation completed. Working length 21mm.","₹2,000"],["4 Aug","36 · RCT","Biomechanical preparation. Temporary filling placed.","₹2,000"],["29 Jul","36","RCT initiated. Access opening done.","₹1,500"]].map(x=><article key={x[0]}><i/><time>{x[0]}</time><div><b>{x[1]}</b><p>{x[2]}</p><small>{x[3]} · Dr. Blessin</small></div></article>)}</section>}
function Teeth(){const nums=[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28,48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];return <section className="panel teeth"><div className="panel-title"><h2>Tooth chart</h2><span>● In progress　● Completed　● Planned</span></div><div className="tooth-grid">{nums.map(n=><button className={n===36?"current":n===16?"planned":""} key={n}><small>{n}</small>♢</button>)}</div><div className="tooth-info"><h3>Tooth 36</h3><dl><div><dt>Diagnosis</dt><dd>Irreversible pulpitis</dd></div><div><dt>Treatment</dt><dd>Root canal treatment</dd></div><div><dt>Status</dt><dd><em>In progress</em></dd></div><div><dt>Visits</dt><dd>3</dd></div></dl></div></section>}
function Plan(){return <section className="panel plan"><div className="panel-title"><h2>Treatment plan</h2><button>＋ Add item</button></div>{[["36","Root canal treatment","In progress","₹6,500"],["16","Composite filling","Planned","₹1,500"],["—","Scaling","Completed","₹1,200"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span><em>{x[2]}</em><strong>{x[3]}</strong></div>)}</section>}
function Payments(){return <section className="panel payments"><div><span><small>Total treatment</small><b>₹9,200</b></span><span><small>Collected</small><b>₹5,500</b></span><span><small>Outstanding</small><b className="red-text">₹3,700</b></span></div><Button>Record payment</Button></section>}

function QuickVisit({done}:{done:()=>void}){const [s,setS]=useState(1);return <section className="quick"><header><button onClick={done}>×</button><b>Quick visit <small>{s} of 4</small></b></header><div className="quick-progress"><i style={{width:`${s*25}%`}}/></div>{s===1&&<div><h1>Who are you seeing?</h1><p className="muted">Search or choose a recent patient.</p><Search/><div className="recent">{pts.slice(0,3).map((p,i)=><button className={i===0?"active":""} key={p.id}><Av p={p} sm/><span><b>{p.name}</b><small>{p.phone}</small></span><i>✓</i></button>)}</div></div>}{s===2&&<div><h1>What are you doing today?</h1><div className="chips"><button>Treatment</button><button>Consultation</button><button>Review</button></div><label>Tooth<input defaultValue="36"/></label><label>Treatment<select><option>Root canal treatment</option><option>Scaling</option><option>Filling</option></select></label><label>Status<select><option>In progress</option><option>Completed</option></select></label></div>}{s===3&&<div><h1>Clinical note</h1><p className="muted">Capture only what matters.</p><textarea defaultValue="36 obturation completed. Patient comfortable. Recall after one week."/><div className="note-tools"><button>🎙 Dictate</button><button>▤ Templates</button><span>83 / 1000</span></div><label>Follow-up<select><option>In 1 week</option><option>Tomorrow</option><option>None</option></select></label></div>}{s===4&&<div><h1>Payment <small>(optional)</small></h1><label>Treatment fee<input defaultValue="₹2,000"/></label><label>Amount received<input defaultValue="₹2,000"/></label><label>Payment method<select><option>UPI</option><option>Cash</option><option>Card</option></select></label><div className="visit-summary"><Av p={pts[0]}/><span><b>Anjali Rao</b><small>36 · Root canal · In progress</small></span></div></div>}<footer>{s>1&&<Button soft onClick={()=>setS(s-1)}>Back</Button>}<Button onClick={()=>s<4?setS(s+1):done()}>{s<4?"Continue":"Save visit"}</Button></footer></section>}
function Calendar({role}:{role:Role}){const [toast,setToast]=useState(false);return <><Title sub="Tuesday, 11 August" action={<Button onClick={()=>setToast(true)}>＋ Appointment</Button>}>Calendar</Title>{toast&&<div className="toast">Appointment form ready for Calendar sync.<button onClick={()=>setToast(false)}>×</button></div>}<section className="panel day-calendar"><div className="times">{["09:00 AM","10:00 AM","11:00 AM","12:00 PM","01:00 PM","02:00 PM","03:00 PM","04:00 PM"].map(x=><span key={x}>{x}</span>)}</div><div className="events">{slots.map((x,i)=><article className={`e${i}`} style={{top:`${50+i*66}px`}} key={x[1]}><b>{x[0]} · {x[1]}</b><span>{x[2]}</span>{role==="assistant"&&<small>{x[3]}</small>}</article>)}</div></section></>}
function Followups(){return <><Title sub="Patients needing attention">Follow-ups</Title><div className="tabs"><button className="active">Today (3)</button><button>Overdue (2)</button><button>This week (8)</button></div><section className="panel patient-list">{pts.slice(0,4).map((p,i)=><button key={p.id}><Av p={p}/><span><b>{p.name}</b><small>{i===0?"Extraction · Review due today":i===1?"Crown · Lab expected tomorrow":"RCT · No visit for 14 days"}</small></span><i>{["10:30 AM","12:00 PM","3:00 PM","Tomorrow"][i]}</i><strong>›</strong></button>)}</section></>}
function ConsultantOverview(){const [period,setPeriod]=useState("This month"),[paid,setPaid]=useState([true,false,true,false]);const consultants:[string,string,number,string][]=[["Dr. Maria Fernandes","Oral surgeon",8,"₹16,000"],["Dr. Nikhil Shah","Endodontist",6,"₹12,500"],["Dr. Reena D’Souza","Orthodontist",5,"₹10,000"],["Dr. Arjun Mehta","Implantologist",3,"₹9,000"]];return <><Title sub="Consultant work and settlements—nothing extra" action={<select className="period" value={period} onChange={e=>setPeriod(e.target.value)}><option>This month</option><option>Last month</option><option>This quarter</option></select>}>Consultant overview</Title><div className="consultant-totals"><article><span>👩‍⚕️</span><small>Consultant visits</small><b>22</b></article><article><span>₹</span><small>Consultant fees</small><b>₹47,500</b></article><article><span>✓</span><small>Settled</small><b>₹25,000</b></article><article><span>◷</span><small>To be settled</small><b>₹22,500</b></article></div><section className="panel consultant-list"><div className="panel-title"><div><h2>Consultants</h2><p>Tap a settlement to update it</p></div><Button soft>＋ Add consultant</Button></div>{consultants.map((c,i)=><article key={c[0]}><span className={`consultant-avatar c${i}`}>{c[0].split(" ").slice(1).map(x=>x[0]).join("")}</span><div><b>{c[0]}</b><small>{c[1]} · {c[2]} visits</small></div><strong>{c[3]}</strong><button className={paid[i]?"settled":"pending"} onClick={()=>setPaid(p=>p.map((v,n)=>n===i?!v:v))}>{paid[i]?"✓ Settled":"Mark settled"}</button></article>)}</section><section className="panel consultant-activity"><div className="panel-title"><h2>Recent consultant cases</h2></div>{[["Today","Anjali Rao","Dr. Nikhil Shah","RCT consultation","₹2,000"],["10 Aug","Suresh Naik","Dr. Maria Fernandes","Surgical extraction","₹3,500"],["8 Aug","Meera Iyer","Dr. Reena D’Souza","Ortho review","₹1,500"]].map(x=><div key={x[1]}><time>{x[0]}</time><span><b>{x[1]}</b><small>{x[3]} · {x[2]}</small></span><strong>{x[4]}</strong></div>)}</section></>}
function More({role,setRole,exit}:{role:Role,setRole:(r:Role)=>void,exit:()=>void}){return <><Title>More</Title><section className="panel profile"><span className="av purple">B</span><span><b>Blessin Dental Studio</b><small>Margao, Goa · {role==="dentist"?"Dr. Blessin":"Anita, Assistant"}</small></span></section><section className="panel menu">{["Treatments","Team & access","Clinic settings","Calendar & reminders","Data export","Billing & subscription","Help & support","Security & privacy"].map(x=><button key={x}>{x}<i>›</i></button>)}<button onClick={()=>setRole(role==="dentist"?"assistant":"dentist")}>Preview {role==="dentist"?"assistant":"dentist"} experience<i>›</i></button><button className="signout" onClick={exit}>Sign out<i>›</i></button></section></>}

export default function Home(){const [ready,setReady]=useState(false),[role,setRole]=useState<Role>("dentist"),[view,setView]=useState<View>("today");if(!ready)return <Onboarding done={()=>setReady(true)}/>;const content=view==="today"?<Today {...{role,setView}}/>:view==="patients"?<Patients/>:view==="calendar"?<Calendar role={role}/>:view==="followups"?<Followups/>:view==="overview"?<ConsultantOverview/>:view==="visit"?<QuickVisit done={()=>setView("today")}/>:<More role={role} setRole={setRole} exit={()=>setView("today")}/>;return <Shell {...{view,setView,role,setRole}}>{content}</Shell>}
