"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import SignaturePad from "./SignaturePad";
import { downloadPdf } from "@/lib/consent/pdf";
import {
  approveTemplateForClinic,
  consentDemoMode,
  createConsentClinic,
  createTemplate,
  createTemplateVersion,
  currentSession,
  demoContext,
  downloadStoredConsent,
  loadConsentContext,
  resendConsentEmail,
  saveClinicProfile,
  saveDoctor,
  saveSignedConsent,
  signInConsent,
  signOutConsent,
  signUpConsent,
  updateDoctor,
  uploadClinicLogo,
  voidSignedConsent,
} from "@/lib/consent/repository";
import type { ClinicContext, ConsentRecord, ConsentTemplate, DoctorSetting, SignatureStroke } from "@/lib/consent/types";

type View = "dashboard" | "new" | "records" | "templates" | "audit" | "settings";
type NewStep = "details" | "review" | "sign" | "success";

const ACKS = [
  "I have read and understood the information above.",
  "I have had an opportunity to ask questions about the proposed treatment.",
];

function Logo({ context }: { context?: ClinicContext | null }) {
  return <div className="dc-logo">{context?.logoUrl ? <img src={context.logoUrl} alt="Clinic logo" style={{ width: 36, height: 36, objectFit: "contain", borderRadius: 10 }} /> : <span>♡</span>}<strong>{context?.clinicName || "DentMemo"}<small>Consent</small></strong></div>;
}

function AuthPanel({ onUser }: { onUser: (user: User) => void }) {
  const [mode, setMode] = useState<"signin" | "signup">("signin");
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setMessage("");
    try {
      const result = mode === "signin" ? await signInConsent(email, password) : await signUpConsent(email, password, fullName);
      if (result.error) throw result.error;
      if (result.data.user && result.data.session) onUser(result.data.user); else setMessage("Check your email to confirm the account, then sign in.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Could not continue."); } finally { setBusy(false); }
  }
  return <main className="dc-auth-page"><section className="dc-auth-card"><Logo /><p className="dc-kicker">DIGITAL DENTAL CONSENT</p><h1>Create. Sign. Email. Retrieve.</h1><p className="dc-muted">A focused consent record system for dental clinics.</p><form onSubmit={submit} className="dc-form">{mode === "signup" && <label>Your name<input required value={fullName} onChange={(e) => setFullName(e.target.value)} /></label>}<label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{message && <div className="dc-alert">{message}</div>}<button className="dc-primary dc-wide" disabled={busy}>{busy ? "Please wait…" : mode === "signin" ? "Sign in" : "Create account"}</button></form><button className="dc-link" onClick={() => setMode(mode === "signin" ? "signup" : "signin")}>{mode === "signin" ? "New clinic? Create an account" : "Already have an account? Sign in"}</button></section></main>;
}

function ClinicSetup({ user, onDone }: { user: User; onDone: () => Promise<void> }) {
  const [clinicName, setClinicName] = useState(""); const [city, setCity] = useState("Goa"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await createConsentClinic(user, clinicName, city); await onDone(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create clinic."); } finally { setBusy(false); } }
  return <main className="dc-auth-page"><section className="dc-auth-card"><Logo /><p className="dc-kicker">ONE-TIME SETUP</p><h1>Create your Consent workspace.</h1><form onSubmit={submit} className="dc-form"><label>Clinic name<input required value={clinicName} onChange={(e) => setClinicName(e.target.value)} /></label><label>City<input value={city} onChange={(e) => setCity(e.target.value)} /></label>{error && <div className="dc-alert">{error}</div>}<button className="dc-primary dc-wide" disabled={busy}>{busy ? "Creating…" : "Continue"}</button></form></section></main>;
}

function Shell({ context, view, setView, children, onSignOut }: { context: ClinicContext; view: View; setView: (v: View) => void; children: React.ReactNode; onSignOut: () => void }) {
  const items: Array<[View,string,string]> = [["dashboard","⌂","Overview"],["new","+","New consent"],["records","▤","Records"],["templates","□","Templates"],["audit","◎","Audit"],["settings","⚙","Settings"]];
  return <div className="dc-app"><aside className="dc-sidebar"><Logo context={context}/><div className="dc-clinic"><span>{context.clinicName.slice(0,1).toUpperCase()}</span><div><b>{context.clinicName}</b><small>{context.city || "Clinic workspace"}</small></div></div><nav>{items.map(([id,icon,label]) => <button key={id} className={view===id?"active":""} onClick={() => setView(id)}><i>{icon}</i>{label}</button>)}</nav><div className="dc-sidebar-bottom"><small className="dc-muted">Signed. Emailed. Retrievable.</small><button className="dc-link" onClick={onSignOut}>Sign out</button></div></aside><header className="dc-mobile-head"><Logo context={context}/><button className="dc-primary" onClick={() => setView("new")}>+ Consent</button></header><main className="dc-workspace">{children}</main><nav className="dc-mobile-nav">{items.slice(0,4).map(([id,icon,label]) => <button key={id} className={view===id?"active":""} onClick={() => setView(id)}><i>{icon}</i><span>{label}</span></button>)}</nav></div>;
}

function Dashboard({ context, onNew, onRecords }: { context: ClinicContext; onNew:()=>void; onRecords:()=>void }) {
  const today=new Date().toDateString(); const now=new Date();
  const signedToday=context.records.filter(r=>r.status==="signed"&&r.signed_at&&new Date(r.signed_at).toDateString()===today).length;
  const signedMonth=context.records.filter(r=>{if(r.status!=="signed"||!r.signed_at)return false;const d=new Date(r.signed_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();}).length;
  return <><div className="dc-title-row"><div><p className="dc-kicker">DENTMEMO CONSENT</p><h1>{context.clinicName}</h1><p className="dc-muted">Create, sign, email and retrieve dental consent records.</p></div><button className="dc-primary" onClick={onNew}>+ New Consent</button></div><section className="dc-metrics"><article><small>Signed today</small><strong>{signedToday}</strong></article><article><small>Signed this month</small><strong>{signedMonth}</strong></article><article><small>Templates ready</small><strong>{context.templates.filter(t=>t.approval_status==="approved").length}</strong></article></section><section className="dc-panel"><div className="dc-panel-head"><div><h2>Recent consents</h2><p>Your recovery archive if the original email is ever deleted.</p></div><button className="dc-link" onClick={onRecords}>View all</button></div>{!context.records.length?<div className="dc-empty"><span>✎</span><b>No signed consents yet</b></div>:<div className="dc-record-list">{context.records.slice(0,6).map(r=><article key={r.id}><div className="dc-record-icon">{r.status==="voided"?"×":"✓"}</div><div><b>{r.patient_name_snapshot}</b><span>{r.procedure_name_snapshot}{r.tooth_numbers?` · Tooth ${r.tooth_numbers}`:""}</span></div><div className="dc-record-meta"><b>{r.consent_number}</b><small>{r.signed_at?new Date(r.signed_at).toLocaleString("en-IN"):"—"}</small></div><em className={r.status==="voided"?"void":""}>{r.status}</em></article>)}</div>}</section></>;
}

function Records({ context, onRefresh }: { context: ClinicContext; onRefresh:()=>Promise<void> }) {
  const [query,setQuery]=useState(""); const [selected,setSelected]=useState<ConsentRecord|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState<string|null>(null);
  const filtered=context.records.filter(r=>`${r.patient_name_snapshot} ${r.patient_mobile_snapshot||""} ${r.consent_number} ${r.doctor_name_snapshot} ${r.procedure_name_snapshot}`.toLowerCase().includes(query.toLowerCase()));
  async function pdf(r:ConsentRecord){setBusy(r.id);setMessage("");try{if(consentDemoMode())throw new Error("Demo mode does not persist archived PDFs.");downloadPdf(await downloadStoredConsent(r),`${r.consent_number}.pdf`);}catch(e){setMessage(e instanceof Error?e.message:"Could not retrieve PDF.");}finally{setBusy(null);}}
  async function resend(r:ConsentRecord){setBusy(r.id);setMessage("");try{await resendConsentEmail(r.id,r.clinic_id);setMessage(`Email resent for ${r.consent_number}.`);await onRefresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not resend.");}finally{setBusy(null);}}
  async function voidRecord(r:ConsentRecord){const reason=window.prompt("Reason for voiding this signed consent?")||"";if(!reason.trim())return;setBusy(r.id);try{await voidSignedConsent(r,reason);setMessage(`${r.consent_number} voided. Original PDF remains preserved.`);await onRefresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not void.");}finally{setBusy(null);}}
  return <><div className="dc-title-row"><div><p className="dc-kicker">RECORDS</p><h1>Consent archive</h1><p className="dc-muted">Final signed PDFs are immutable and retrievable.</p></div></div><input className="dc-search" placeholder="Search patient, phone, ID, doctor or procedure" value={query} onChange={e=>setQuery(e.target.value)}/>{message&&<div className="dc-alert">{message}</div>}<section className="dc-panel"><div className="dc-record-list">{filtered.map(r=><article key={r.id}><div className="dc-record-icon">{r.status==="voided"?"×":"✓"}</div><div><b>{r.patient_name_snapshot}</b><span>{r.procedure_name_snapshot} · {r.doctor_name_snapshot}</span></div><div className="dc-record-meta"><b>{r.consent_number}</b><small>{r.email_status==="sent"?"Email sent":r.email_status==="failed"?"Email failed":"Email pending"}</small></div><div className="dc-actions"><button className="dc-link" onClick={()=>setSelected(r)}>View</button><button className="dc-link" disabled={busy===r.id} onClick={()=>void pdf(r)}>PDF</button>{r.status==="signed"&&<button className="dc-link" disabled={busy===r.id} onClick={()=>void resend(r)}>Resend</button>}{r.status==="signed"&&context.role!=="assistant"&&<button className="dc-link" disabled={busy===r.id} onClick={()=>void voidRecord(r)}>Void</button>}</div></article>)}</div></section>{selected&&<section className="dc-panel dc-top-gap"><div className="dc-panel-head"><div><small>{selected.consent_number}</small><h2>{selected.consent_title_snapshot}</h2></div><button className="dc-link" onClick={()=>setSelected(null)}>Close</button></div><div className="dc-success-meta"><div><small>Patient</small><b>{selected.patient_name_snapshot}</b></div><div><small>Doctor</small><b>{selected.doctor_name_snapshot}</b></div><div><small>Template</small><b>v{selected.template_version||1}</b></div></div><div className="dc-consent-copy">{selected.consent_text_snapshot}</div>{selected.void_reason&&<div className="dc-alert">Voided: {selected.void_reason}</div>}</section>}</>;
}

function Templates({ context, onRefresh }: { context: ClinicContext; onRefresh:()=>Promise<void> }) {
  const [message,setMessage]=useState(""); const [showNew,setShowNew]=useState(false); const [editing,setEditing]=useState<ConsentTemplate|null>(null);
  const [title,setTitle]=useState(""); const [key,setKey]=useState(""); const [text,setText]=useState(""); const [locale,setLocale]=useState("en-IN"); const owner=context.role==="owner";
  function openVersion(t:ConsentTemplate){setEditing(t);setTitle(t.display_title);setText(t.consent_text);setLocale(t.locale);setShowNew(false);}
  async function create(event:FormEvent){event.preventDefault();try{await createTemplate(context.clinicId,{title,procedureKey:key,text,locale});setMessage("Template created as Needs review.");setShowNew(false);setTitle("");setKey("");setText("");await onRefresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not create template.");}}
  async function version(event:FormEvent){event.preventDefault();if(!editing)return;try{await createTemplateVersion(context.clinicId,editing,{title,text,locale});setMessage("New template version created as Needs review. Existing signed records remain on the old version.");setEditing(null);await onRefresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not create version.");}}
  async function approve(t:ConsentTemplate){try{await approveTemplateForClinic(context.clinicId,t);setMessage(`${t.display_title} v${t.version} approved.`);await onRefresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not approve.");}}
  return <><div className="dc-title-row"><div><p className="dc-kicker">TEMPLATES</p><h1>Consent templates</h1><p className="dc-muted">Create clinic-specific forms. Changes create new versions, never rewrite history.</p></div>{owner&&<button className="dc-primary" onClick={()=>{setShowNew(true);setEditing(null);}}>+ New template</button>}</div>{message&&<div className="dc-alert">{message}</div>}{showNew&&<section className="dc-panel dc-top-gap"><h2>Create template</h2><form className="dc-form" onSubmit={create}><div className="dc-two-col"><label>Template name<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Procedure key<input required placeholder="e.g. crown_bridge" value={key} onChange={e=>setKey(e.target.value)}/></label></div><label>Consent wording<textarea required minLength={40} rows={8} value={text} onChange={e=>setText(e.target.value)}/></label><label>Language<select value={locale} onChange={e=>setLocale(e.target.value)}><option value="en-IN">English</option><option value="hi-IN">Hindi</option><option value="kok-IN">Konkani</option><option value="mr-IN">Marathi</option></select></label><div className="dc-actions"><button className="dc-primary">Create</button><button type="button" className="dc-secondary" onClick={()=>setShowNew(false)}>Cancel</button></div></form></section>}{editing&&<section className="dc-panel dc-top-gap"><h2>Create new version of {editing.display_title}</h2><p className="dc-muted">Version {editing.version} remains unchanged for historical signed records.</p><form className="dc-form" onSubmit={version}><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Consent wording<textarea required minLength={40} rows={8} value={text} onChange={e=>setText(e.target.value)}/></label><label>Language<input value={locale} onChange={e=>setLocale(e.target.value)}/></label><div className="dc-actions"><button className="dc-primary">Create new version</button><button type="button" className="dc-secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form></section>}<div className="dc-template-grid dc-top-gap">{context.templates.map(t=><article className="dc-panel" key={t.id}><div className="dc-panel-head"><div><small>{t.procedure_key.replaceAll("_"," ").toUpperCase()}</small><h2>{t.display_title}</h2></div><em className={t.approval_status==="approved"?"dc-approved":"dc-review"}>{t.approval_status==="approved"?"Approved":"Needs review"}</em></div><p>{t.consent_text}</p><footer><span>Version {t.version}</span><span>{t.locale}</span></footer>{owner&&<div className="dc-actions dc-top-gap">{t.approval_status!=="approved"&&<button className="dc-secondary" onClick={()=>void approve(t)}>Approve</button>}{t.clinic_id===context.clinicId&&<button className="dc-link" onClick={()=>openVersion(t)}>New version</button>}</div>}</article>)}</div></>;
}

function Audit({ context }: { context: ClinicContext }) {
  const [query,setQuery]=useState("");
  const rows=context.audit.filter(a=>`${a.event_type} ${a.actor_display_name||""} ${a.entity_type||""} ${JSON.stringify(a.metadata)}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="dc-title-row"><div><p className="dc-kicker">AUDIT</p><h1>Activity log</h1><p className="dc-muted">Who did what, and when. Audit entries are append-only.</p></div></div><input className="dc-search" placeholder="Search action, user or entity" value={query} onChange={e=>setQuery(e.target.value)}/><section className="dc-panel"><div className="dc-record-list">{rows.map(a=><article key={a.id}><div className="dc-record-icon">•</div><div><b>{a.event_type.replaceAll("_"," ")}</b><span>{a.actor_display_name||"System"}{a.entity_type?` · ${a.entity_type}`:""}</span></div><div className="dc-record-meta"><b>{new Date(a.created_at).toLocaleDateString("en-IN")}</b><small>{new Date(a.created_at).toLocaleTimeString("en-IN")}</small></div><em>{a.consent_id?"Consent":"Account"}</em></article>)}</div>{!rows.length&&<div className="dc-empty"><b>No matching activity</b></div>}</section></>;
}

function Settings({ context, onRefresh }: { context: ClinicContext; onRefresh:()=>Promise<void> }) {
  const owner=context.role==="owner"; const [name,setName]=useState(context.clinicName); const [city,setCity]=useState(context.city||""); const [address,setAddress]=useState(context.address||""); const [phone,setPhone]=useState(context.phone||""); const [email,setEmail]=useState(context.clinicEmail||""); const [message,setMessage]=useState(""); const [editingDoctor,setEditingDoctor]=useState<DoctorSetting|null>(null); const [doctorName,setDoctorName]=useState(""); const [reg,setReg]=useState(""); const [doctorEmail,setDoctorEmail]=useState("");
  async function profile(e:FormEvent){e.preventDefault();try{await saveClinicProfile(context.clinicId,{name,city,address,phone,email});setMessage("Clinic profile updated.");await onRefresh();}catch(err){setMessage(err instanceof Error?err.message:"Could not update clinic.");}}
  async function logo(file?:File){if(!file)return;try{await uploadClinicLogo(context.clinicId,file);setMessage("Clinic logo updated.");await onRefresh();}catch(err){setMessage(err instanceof Error?err.message:"Could not upload logo.");}}
  function edit(d:DoctorSetting){setEditingDoctor(d);setDoctorName(d.doctor_name);setReg(d.registration_number||"");setDoctorEmail(d.email);}
  async function doctor(e:FormEvent){e.preventDefault();try{if(editingDoctor)await updateDoctor(context.clinicId,editingDoctor,{doctorName,registrationNumber:reg,email:doctorEmail});else await saveDoctor(context.clinicId,{doctorName,registrationNumber:reg,email:doctorEmail});setMessage(editingDoctor?"Doctor updated.":"Doctor added.");setEditingDoctor(null);setDoctorName("");setReg("");setDoctorEmail("");await onRefresh();}catch(err){setMessage(err instanceof Error?err.message:"Could not save doctor.");}}
  return <><div className="dc-title-row"><div><p className="dc-kicker">SETTINGS</p><h1>Clinic identity & users</h1><p className="dc-muted">These details identify the clinic and treating doctor on every consent workflow.</p></div></div>{message&&<div className="dc-alert">{message}</div>}<div className="dc-settings-grid dc-top-gap"><section className="dc-panel"><h2>Clinic profile</h2>{context.logoUrl&&<img src={context.logoUrl} alt="Clinic logo" style={{maxWidth:120,maxHeight:72,objectFit:"contain",margin:"12px 0"}}/>}{owner&&<form className="dc-form" onSubmit={profile}><label>Clinic logo<input type="file" accept="image/*" onChange={e=>void logo(e.target.files?.[0])}/></label><label>Clinic name<input required value={name} onChange={e=>setName(e.target.value)}/></label><div className="dc-two-col"><label>City<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><label>Address<textarea rows={3} value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Clinic email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="dc-primary">Save clinic profile</button></form>}</section><section className="dc-panel"><h2>Doctors</h2><div className="dc-doctors">{context.doctors.map(d=><article key={d.id}><span>{d.doctor_name.slice(0,1)}</span><div><b>{d.doctor_name}</b><small>{d.registration_number||"No registration"} · {d.email}</small></div>{owner&&<button className="dc-link" onClick={()=>edit(d)}>Edit</button>}</article>)}</div>{owner&&<form className="dc-form dc-top-gap" onSubmit={doctor}><h2>{editingDoctor?"Edit doctor":"Add doctor"}</h2><label>Doctor name<input required value={doctorName} onChange={e=>setDoctorName(e.target.value)}/></label><label>Dental registration number<input value={reg} onChange={e=>setReg(e.target.value)}/></label><label>Email for signed PDFs<input required type="email" value={doctorEmail} onChange={e=>setDoctorEmail(e.target.value)}/></label><div className="dc-actions"><button className="dc-primary">{editingDoctor?"Save changes":"Add doctor"}</button>{editingDoctor&&<button type="button" className="dc-secondary" onClick={()=>setEditingDoctor(null)}>Cancel</button>}</div></form>}</section></div><section className="dc-panel dc-top-gap"><div className="dc-panel-head"><div><h2>Workspace users</h2><p>Each person should use their own login so actions can be attributed correctly.</p></div></div><div className="dc-record-list">{context.members.map(m=><article key={m.user_id}><div className="dc-record-icon">{m.display_name.slice(0,1).toUpperCase()}</div><div><b>{m.display_name}</b><span>{m.role}</span></div><div className="dc-record-meta"><b>{m.active?"Active":"Inactive"}</b></div><em>{m.role}</em></article>)}</div></section></>;
}

function NewConsent({ context,onSaved,onCancel }:{context:ClinicContext;onSaved:(r:ConsentRecord)=>Promise<void>;onCancel:()=>void}){
  const [step,setStep]=useState<NewStep>("details"); const [patientName,setPatientName]=useState(""); const [mobile,setMobile]=useState(""); const [dob,setDob]=useState(""); const [doctorId,setDoctorId]=useState(context.doctors[0]?.id||""); const [templateId,setTemplateId]=useState(context.templates.find(t=>t.approval_status==="approved")?.id||""); const [tooth,setTooth]=useState(""); const [notes,setNotes]=useState(""); const [guardian,setGuardian]=useState(false); const [guardianName,setGuardianName]=useState(""); const [relationship,setRelationship]=useState(""); const [acks,setAcks]=useState<string[]>([]); const [signature,setSignature]=useState<SignatureStroke[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [saved,setSaved]=useState<{record:ConsentRecord;pdf:Uint8Array;emailError?:string}|null>(null);
  const doctor=context.doctors.find(d=>d.id===doctorId); const template=context.templates.find(t=>t.id===templateId);
  async function submit(){if(!doctor||!template||!signature.length)return;setBusy(true);try{const result=await saveSignedConsent({clinicId:context.clinicId,clinicName:context.clinicName,patientName,patientMobile:mobile,patientDob:dob,doctor,template,procedureNotes:notes,toothNumbers:tooth,acknowledgements:acks,signerType:guardian?"guardian":"patient",signerName:guardian?guardianName:patientName,signerRelationship:relationship,signature});setSaved(result);setStep("success");await onSaved(result.record);}catch(e){setError(e instanceof Error?e.message:"Could not complete consent.");}finally{setBusy(false);}}
  if(step==="success"&&saved)return <section className="dc-success"><span>✓</span><p className="dc-kicker">CONSENT COMPLETED</p><h1>{saved.record.consent_number}</h1><h2>{saved.record.patient_name_snapshot}</h2><p>{saved.emailError?"Signed and stored. Email delivery needs retry.":"Signed, stored and emailed."}</p><div className="dc-actions"><button className="dc-primary" onClick={()=>downloadPdf(saved.pdf,`${saved.record.consent_number}.pdf`)}>Download PDF</button><button className="dc-secondary" onClick={onCancel}>Done</button></div></section>;
  if(step==="review"&&doctor&&template)return <section className="dc-patient-screen"><div className="dc-patient-top"><button className="dc-link" onClick={()=>setStep("details")}>← Back</button><Logo context={context}/><span>Patient review</span></div><article className="dc-document"><div className="dc-document-head"><div><small>{context.clinicName}</small><h1>{template.display_title}</h1></div><span>v{template.version}</span></div><dl><div><dt>Patient</dt><dd>{patientName}</dd></div><div><dt>Doctor</dt><dd>{doctor.doctor_name}</dd></div>{tooth&&<div><dt>Tooth / teeth</dt><dd>{tooth}</dd></div>}</dl><div className="dc-consent-copy">{template.consent_text}</div><div className="dc-ack-list">{ACKS.map(a=><label key={a}><input type="checkbox" checked={acks.includes(a)} onChange={()=>setAcks(x=>x.includes(a)?x.filter(i=>i!==a):[...x,a])}/><span>{a}</span></label>)}</div><label className="dc-guardian-toggle"><input type="checkbox" checked={guardian} onChange={e=>setGuardian(e.target.checked)}/><span>Parent / guardian is signing</span></label>{guardian&&<div className="dc-two-col"><label>Guardian name<input value={guardianName} onChange={e=>setGuardianName(e.target.value)}/></label><label>Relationship<input value={relationship} onChange={e=>setRelationship(e.target.value)}/></label></div>}<button className="dc-primary dc-wide" disabled={!ACKS.every(a=>acks.includes(a))||(guardian&&(!guardianName.trim()||!relationship.trim()))} onClick={()=>setStep("sign")}>Continue to Sign</button></article></section>;
  if(step==="sign"&&doctor&&template)return <section className="dc-patient-screen"><div className="dc-patient-top"><button className="dc-link" onClick={()=>setStep("review")}>← Back</button><Logo context={context}/><span>Final step</span></div><div className="dc-sign-card"><p className="dc-kicker">PATIENT SIGNATURE</p><h1>{guardian?"Parent / guardian signature":"Please sign below"}</h1><p className="dc-muted">Use your finger or stylus.</p><SignaturePad value={signature} onChange={setSignature}/>{error&&<div className="dc-alert">{error}</div>}<button className="dc-primary dc-wide" disabled={!signature.length||busy} onClick={()=>void submit()}>{busy?"Completing…":"Accept & Submit"}</button></div></section>;
  return <><div className="dc-title-row"><div><p className="dc-kicker">NEW CONSENT</p><h1>Patient & treatment</h1><p className="dc-muted">Enter the essentials, then hand the tablet to the patient.</p></div><button className="dc-link" onClick={onCancel}>Cancel</button></div><section className="dc-panel dc-form-panel"><form className="dc-form" onSubmit={e=>{e.preventDefault();if(!doctor)return setError("Select a doctor.");if(!template)return setError("Select an approved template.");setError("");setStep("review");}}><h2>Patient</h2><div className="dc-two-col"><label>Patient name<input required value={patientName} onChange={e=>setPatientName(e.target.value)}/></label><label>Mobile<input value={mobile} onChange={e=>setMobile(e.target.value)}/></label></div><label>Date of birth<input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><hr/><h2>Treatment</h2><div className="dc-two-col"><label>Treating doctor<select required value={doctorId} onChange={e=>setDoctorId(e.target.value)}><option value="">Select doctor</option>{context.doctors.map(d=><option key={d.id} value={d.id}>{d.doctor_name}</option>)}</select></label><label>Consent template<select required value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Select template</option>{context.templates.filter(t=>t.approval_status==="approved").map(t=><option key={t.id} value={t.id}>{t.display_title} · v{t.version}</option>)}</select></label></div><div className="dc-two-col"><label>Tooth number(s)<input value={tooth} onChange={e=>setTooth(e.target.value)} placeholder="e.g. 16, 17"/></label><label>Procedure notes<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{error&&<div className="dc-alert">{error}</div>}<button className="dc-primary">Review Consent →</button></form></section></>;
}

export default function ConsentApp(){
  const [user,setUser]=useState<User|null>(null); const [context,setContext]=useState<ClinicContext|null>(null); const [view,setView]=useState<View>("dashboard"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const isDemo=useMemo(()=>consentDemoMode(),[]);
  async function refresh(target=user){if(isDemo){setContext(c=>c||demoContext());setLoading(false);return;}if(!target){setContext(null);setLoading(false);return;}try{setContext(await loadConsentContext(target));}catch(e){setError(e instanceof Error?e.message:"Could not load Consent.");}finally{setLoading(false);}}
  useEffect(()=>{let cancelled=false;void(async()=>{if(isDemo){if(!cancelled){setContext(demoContext());setLoading(false);}return;}const session=await currentSession();if(!cancelled){setUser(session?.user??null);await refresh(session?.user??null);}})();return()=>{cancelled=true};},[isDemo]);
  if(loading)return <div className="dc-loading">Loading DentMemo Consent…</div>; if(error&&!context)return <div className="dc-loading">{error}</div>; if(!isDemo&&!user)return <AuthPanel onUser={u=>{setUser(u);setLoading(true);void refresh(u);}}/>; if(!context&&user)return <ClinicSetup user={user} onDone={()=>refresh(user)}/>; if(!context)return null;
  async function logout(){if(!isDemo)await signOutConsent();setUser(null);setContext(isDemo?demoContext():null);}
  return <Shell context={context} view={view} setView={setView} onSignOut={()=>void logout()}>{isDemo&&<div className="dc-demo-banner">Demo mode · do not enter real patient information.</div>}{view==="dashboard"&&<Dashboard context={context} onNew={()=>setView("new")} onRecords={()=>setView("records")}/>} {view==="records"&&<Records context={context} onRefresh={()=>refresh(user)}/>} {view==="templates"&&<Templates context={context} onRefresh={()=>refresh(user)}/>} {view==="audit"&&<Audit context={context}/>} {view==="settings"&&<Settings context={context} onRefresh={()=>refresh(user)}/>} {view==="new"&&<NewConsent context={context} onSaved={async()=>{await refresh(user)}} onCancel={()=>setView("dashboard")}/>}</Shell>;
}
