create index dm_clinics_owner_idx on public.dm_clinics(owner_user_id);
create index dm_members_user_idx on public.dm_clinic_members(user_id);
create index dm_appointments_patient_idx on public.dm_appointments(patient_id);
create index dm_appointments_practitioner_idx on public.dm_appointments(practitioner_user_id);
create index dm_treatment_plans_clinic_idx on public.dm_treatment_plans(clinic_id);
create index dm_visits_clinic_idx on public.dm_visits(clinic_id);
create index dm_visits_appointment_idx on public.dm_visits(appointment_id);
create index dm_visits_practitioner_idx on public.dm_visits(practitioner_user_id);
create index dm_visit_treatments_visit_idx on public.dm_visit_treatments(visit_id);
create index dm_visit_treatments_plan_idx on public.dm_visit_treatments(treatment_plan_id);
create index dm_payments_clinic_idx on public.dm_payments(clinic_id);
create index dm_payments_visit_idx on public.dm_payments(visit_id);
create index dm_payments_recorded_by_idx on public.dm_payments(recorded_by);
create index dm_reminders_clinic_idx on public.dm_reminders(clinic_id);
create index dm_reminders_appointment_idx on public.dm_reminders(appointment_id);
create index dm_audit_clinic_date_idx on public.dm_audit_log(clinic_id,created_at desc);
create index dm_audit_actor_idx on public.dm_audit_log(actor_user_id);
